In [4]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [51]:
df.loc[:, 'salary_rate':'salary_hour_avg'].dropna(subset='salary_rate')

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]

In [49]:
df.dropna(subset= ['salary_rate'])
df.dropna(subset= ['salary_year_avg'])
df.dropna(subset= ['salary_hour_avg'])

             job_title_short  ...                                    job_type_skills
43      Senior Data Engineer  ...  {'databases': ['sql server'], 'programming': [...
51      Senior Data Engineer  ...  {'cloud': ['aws', 'databricks'], 'libraries': ...
253            Data Engineer  ...  {'cloud': ['aws', 'gcp'], 'databases': ['mysql...
294             Data Analyst  ...                                               None
340             Data Analyst  ...  {'analyst_tools': ['tableau', 'looker', 'word'...
...                      ...  ...                                                ...
784068         Data Engineer  ...  {'cloud': ['snowflake', 'aws'], 'programming':...
784267  Senior Data Engineer  ...  {'cloud': ['redshift', 'snowflake', 'aws', 'az...
785111  Senior Data Engineer  ...  {'cloud': ['aws', 'azure', 'databricks', 'reds...
785476        Data Scientist  ...          {'cloud': ['databricks', 'azure', 'aws']}
785492        Data Scientist  ...  {'libraries': ['pyspark'], 'programming': ['py...

[10662 rows x 17 columns]

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB